FROM node:24-alpine AS base
ENV NODE_ENV=development

FROM base AS deps
WORKDIR /app
COPY package*.json ./
RUN npm ci --ignore-scripts --no-audit --no-fund --omit=dev

FROM base AS runner
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
EXPOSE 3000
CMD sh -c "npm run dev"
