FROM python:3.13-alpine

WORKDIR /app

COPY requirements/common.txt requirements/common.txt
COPY requirements/prod.txt requirements/prod.txt

RUN pip install -r requirements/prod.txt

COPY scripts scripts
COPY cli cli
COPY src src
COPY pyproject.toml pyproject.toml

EXPOSE 8000

CMD sh -c "./scripts/cmd/prod"
