#!/bin/sh

# Run migrations
alembic upgrade head

# Create superuser
python -m cli superuser create \
  --username $SUPERUSER_USERNAME \
  --password $SUPERUSER_PASSWORD

# Populate users
python -m cli populate users

# Start development server
uvicorn src.app:app --host 0.0.0.0 --port 8000 --reload
