#!/bin/sh

# Run migrations
alembic upgrade head

# Create superuser
python -m cli superuser create \
  --username $SUPERUSER_USERNAME \
  --password $SUPERUSER_PASSWORD

# Start production server
uvicorn src.app:app --host 0.0.0.0 --port 8000 --forwarded-allow-ips="*" --proxy-headers
