"""add superuser

Revision ID: 7707e3c6302b
Revises: 535098875eea
Create Date: 2025-10-19 22:14:47.667994

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "7707e3c6302b"
down_revision: str | Sequence[str] | None = "535098875eea"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("is_superuser", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "is_superuser")
    # ### end Alembic commands ###
