"""request_id in resume

Revision ID: a22a4da95ee6
Revises: ac380854d68a
Create Date: 2025-11-22 20:45:51.324920

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a22a4da95ee6"
down_revision: str | Sequence[str] | None = "ac380854d68a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("resume", sa.Column("request_id", sa.UUID(), nullable=True))
    op.create_unique_constraint(None, "resume", ["request_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "resume", type_="unique")  # type: ignore
    op.drop_column("resume", "request_id")
    # ### end Alembic commands ###
