"""skill name not unique now

Revision ID: ac380854d68a
Revises: 5440c93be81c
Create Date: 2025-11-22 15:37:58.037251

"""

from typing import Sequence

from alembic import op

revision: str = "ac380854d68a"
down_revision: str | Sequence[str] | None = "5440c93be81c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("skill_name_key"), "skill", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f("skill_name_key"), "skill", ["name"], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
