{
 "title": "Оценки пользователей",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "После 2 переоценки",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(user_rating_3_bucket[1d])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "После переоценки",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(user_rating_2_bucket[1d])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Оценки во времени",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(user_rating_1_sum[5m]) / rate(user_rating_1_count[5m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(user_rating_2_sum[5m]) / rate(user_rating_2_count[5m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(user_rating_3_sum[5m]) / rate(user_rating_3_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Оценка после заполнения формы",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(user_rating_1_bucket[1d])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}