/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/auth/register": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Register */
    post: operations["register_auth_register_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Login */
    post: operations["login_auth_login_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/users/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Current User */
    get: operations["get_current_user_users_me_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/users/me/username": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update Current User Username */
    patch: operations["update_current_user_username_users_me_username_patch"];
    trace?: never;
  };
  "/users/me/password": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update Current User Password */
    patch: operations["update_current_user_password_users_me_password_patch"];
    trace?: never;
  };
  "/users": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Users */
    get: operations["get_users_users_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/users/{username}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get User */
    get: operations["get_user_users__username__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/resumes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Load Resume */
    get: operations["load_resume_resumes_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/resumes/analyze/salary_fork": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Get Salary Fork */
    post: operations["get_salary_fork_resumes_analyze_salary_fork_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/resumes/analyze/recommendations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Get Recommendations */
    post: operations["get_recommendations_resumes_analyze_recommendations_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/parse/pdf": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Parse Resume From Pdf */
    post: operations["parse_resume_from_pdf_parse_pdf_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/resumes{ResumeID}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Load Resume */
    get: operations["load_resume_resumes_ResumeID__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/resumes/skills": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Skills By Role */
    get: operations["get_skills_by_role_resumes_skills_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * AccessTokenResponse
     * @description Represents a response containing access token and its expiration datetime.
     */
    AccessTokenResponse: {
      /** Access Token */
      access_token: string;
      /**
       * Token Type
       * @default bearer
       */
      token_type: string;
      /**
       * Expires At
       * Format: date-time
       */
      expires_at: string;
    };
    /** Body_login_auth_login_post */
    Body_login_auth_login_post: {
      /** Grant Type */
      grant_type?: string | null;
      /** Username */
      username: string;
      /** Password */
      password: string;
      /**
       * Scope
       * @default
       */
      scope: string;
      /** Client Id */
      client_id?: string | null;
      /** Client Secret */
      client_secret?: string | null;
    };
    /** Body_parse_resume_from_pdf_parse_pdf_post */
    Body_parse_resume_from_pdf_parse_pdf_post: {
      /**
       * File
       * Format: binary
       */
      file: string;
    };
    /**
     * CurrentUserResponse
     * @description Represents the private response data for a user.
     */
    CurrentUserResponse: {
      /**
       * Id
       * Format: uuid4
       */
      id: string;
      /**
       * Username
       * @example username
       */
      username: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** LLMResponse */
    LLMResponse: {
      /** Recommendations */
      recommendations: components["schemas"]["RecommendationDTO"][];
      /**
       * Quality
       * @enum {string}
       */
      quality: "poor" | "moderate" | "good";
    };
    /** OptionalResumes */
    OptionalResumes: {
      /** Role */
      role: string | null;
      /** Skills */
      skills: string[];
      /** Experience */
      experience: number | null;
      /** Location */
      location: string | null;
    };
    /** PaginationResponse */
    PaginationResponse: {
      /** Total Items */
      total_items: number;
      /** Total Pages */
      total_pages: number;
      /** Current Page */
      current_page: number;
      /** Per Page */
      per_page: number;
      /** Has Next Page */
      has_next_page: boolean;
      /** Has Prev Page */
      has_prev_page: boolean;
      /** Next Page */
      next_page: number | null;
      /** Prev Page */
      prev_page: number | null;
    };
    /** RecommendationDTO */
    RecommendationDTO: {
      /** Title */
      title: string;
      /** Subtitle */
      subtitle: string;
      /** Result */
      result: string;
    };
    /** ResumeAnalyzedResponse */
    ResumeAnalyzedResponse: {
      /** Request Id */
      request_id?: string | null;
      /** Role */
      role: string;
      /** Experience */
      experience: number;
      /** Location */
      location: string;
      /** Skills */
      skills: string[];
      salary?: components["schemas"]["SalaryDTO"] | null;
      /** Quality */
      quality?: ("poor" | "moderate" | "good") | null;
      /** Recommendations */
      recommendations?: components["schemas"]["RecommendationDTO"][] | null;
    };
    /** ResumeDTO */
    ResumeDTO: {
      /** Request Id */
      request_id: string | null;
      /** Role */
      role: string;
      /** Skills */
      skills: string[];
      /** Experience */
      experience: number;
      /** Location */
      location: string;
    };
    /** ResumeSkillsResponse */
    ResumeSkillsResponse: {
      /** Role */
      role: string;
      /** Skills */
      skills: string[];
    };
    /** SalaryDTO */
    SalaryDTO: {
      /** From */
      from: number;
      /** To */
      to: number;
    };
    /**
     * UserRegistrationRequest
     * @description Represents the user registration details.
     */
    UserRegistrationRequest: {
      /**
       * Username
       * @example username
       */
      username: string;
      /**
       * Password
       * @example password
       */
      password: string;
    };
    /**
     * UserResponse
     * @description Represents the public response data for a user.
     */
    UserResponse: {
      /**
       * Id
       * Format: uuid4
       */
      id: string;
      /**
       * Username
       * @example username
       */
      username: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /**
     * UserUpdatePasswordRequest
     * @description Represents the user password request details.
     */
    UserUpdatePasswordRequest: {
      /**
       * Old Password
       * @example password
       */
      old_password: string;
      /**
       * New Password
       * @example password
       */
      new_password: string;
    };
    /**
     * UserUsernameRequest
     * @description Represents the user username request details.
     */
    UserUsernameRequest: {
      /**
       * Username
       * @example username
       */
      username: string;
    };
    /**
     * UsersPaginationResponse
     * @description Represents the public response data for a list of users.
     */
    UsersPaginationResponse: {
      /** Users */
      users: components["schemas"]["UserResponse"][];
      pagination: components["schemas"]["PaginationResponse"];
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type AccessTokenResponse = components["schemas"]["AccessTokenResponse"];
export type BodyLoginAuthLoginPost =
  components["schemas"]["Body_login_auth_login_post"];
export type BodyParseResumeFromPdfParsePdfPost =
  components["schemas"]["Body_parse_resume_from_pdf_parse_pdf_post"];
export type CurrentUserResponse = components["schemas"]["CurrentUserResponse"];
export type HttpValidationError = components["schemas"]["HTTPValidationError"];
export type LlmResponse = components["schemas"]["LLMResponse"];
export type OptionalResumes = components["schemas"]["OptionalResumes"];
export type PaginationResponse = components["schemas"]["PaginationResponse"];
export type RecommendationDto = components["schemas"]["RecommendationDTO"];
export type ResumeAnalyzedResponse =
  components["schemas"]["ResumeAnalyzedResponse"];
export type ResumeDto = components["schemas"]["ResumeDTO"];
export type ResumeSkillsResponse =
  components["schemas"]["ResumeSkillsResponse"];
export type SalaryDto = components["schemas"]["SalaryDTO"];
export type UserRegistrationRequest =
  components["schemas"]["UserRegistrationRequest"];
export type UserResponse = components["schemas"]["UserResponse"];
export type UserUpdatePasswordRequest =
  components["schemas"]["UserUpdatePasswordRequest"];
export type UserUsernameRequest = components["schemas"]["UserUsernameRequest"];
export type UsersPaginationResponse =
  components["schemas"]["UsersPaginationResponse"];
export type ValidationError = components["schemas"]["ValidationError"];
export type $defs = Record<string, never>;
export interface operations {
  register_auth_register_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserRegistrationRequest"];
      };
    };
    responses: {
      /** @description Registraton was successful */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AccessTokenResponse"];
        };
      };
      /** @description Username already registered */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  login_auth_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/x-www-form-urlencoded": components["schemas"]["Body_login_auth_login_post"];
      };
    };
    responses: {
      /** @description Login was successful */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AccessTokenResponse"];
        };
      };
      /** @description Incorrect username or password */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_current_user_users_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CurrentUserResponse"];
        };
      };
      /** @description Failed to verify credentials */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description User not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  update_current_user_username_users_me_username_patch: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserUsernameRequest"];
      };
    };
    responses: {
      /** @description Username successfully updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CurrentUserResponse"];
        };
      };
      /** @description Failed to verify credentials */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description User not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Username already registered */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_current_user_password_users_me_password_patch: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserUpdatePasswordRequest"];
      };
    };
    responses: {
      /** @description Password successfully updated */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Failed to verify credentials or incorrect password */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description User not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_users_users_get: {
    parameters: {
      query?: {
        q?: string | null;
        offset?: number;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UsersPaginationResponse"];
        };
      };
      /** @description No users found matching the provided search parameters */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_user_users__username__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        username: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserResponse"];
        };
      };
      /** @description No user found with the provided username */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  load_resume_resumes_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ResumeAnalyzedResponse"][];
        };
      };
    };
  };
  get_salary_fork_resumes_analyze_salary_fork_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ResumeDTO"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SalaryDTO"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_recommendations_resumes_analyze_recommendations_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ResumeDTO"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LLMResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  parse_resume_from_pdf_parse_pdf_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_parse_resume_from_pdf_parse_pdf_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OptionalResumes"];
        };
      };
      /** @description Failed to parse resume */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description File size exceeded maximum resume size */
      413: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description File type must be application/pdf */
      415: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  load_resume_resumes_ResumeID__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        ResumeID: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ResumeAnalyzedResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_skills_by_role_resumes_skills_get: {
    parameters: {
      query: {
        role: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ResumeSkillsResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
