/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/auth/register": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Register */
    post: operations["register_auth_register_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Login */
    post: operations["login_auth_login_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/users/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Current User */
    get: operations["get_current_user_users_me_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/users/me/username": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update Current User Username */
    patch: operations["update_current_user_username_users_me_username_patch"];
    trace?: never;
  };
  "/users/me/password": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update Current User Password */
    patch: operations["update_current_user_password_users_me_password_patch"];
    trace?: never;
  };
  "/users": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Users */
    get: operations["get_users_users_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/users/{username}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get User */
    get: operations["get_user_users__username__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/resumes/analyze": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Load Resume */
    post: operations["load_resume_resumes_analyze_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * AccessTokenResponse
     * @description Represents a response containing access token and its expiration datetime.
     */
    AccessTokenResponse: {
      /** Access Token */
      access_token: string;
      /**
       * Token Type
       * @default bearer
       */
      token_type: string;
      /**
       * Expires At
       * Format: date-time
       */
      expires_at: string;
    };
    /** Body_login_auth_login_post */
    Body_login_auth_login_post: {
      /** Grant Type */
      grant_type?: string | null;
      /** Username */
      username: string;
      /** Password */
      password: string;
      /**
       * Scope
       * @default
       */
      scope: string;
      /** Client Id */
      client_id?: string | null;
      /** Client Secret */
      client_secret?: string | null;
    };
    /**
     * CurrentUserResponse
     * @description Represents the private response data for a user.
     */
    CurrentUserResponse: {
      /**
       * Id
       * Format: uuid4
       */
      id: string;
      /**
       * Username
       * @example username
       */
      username: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** Experience */
    Experience: {
      /** From */
      from: number;
      /** To */
      to: number;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** PaginationResponse */
    PaginationResponse: {
      /** Total Items */
      total_items: number;
      /** Total Pages */
      total_pages: number;
      /** Current Page */
      current_page: number;
      /** Per Page */
      per_page: number;
      /** Has Next Page */
      has_next_page: boolean;
      /** Has Prev Page */
      has_prev_page: boolean;
      /** Next Page */
      next_page: number | null;
      /** Prev Page */
      prev_page: number | null;
    };
    /** Recommendation */
    Recommendation: {
      /** Title */
      title: string;
      /** Subtitle */
      subtitle: string;
      /** Result */
      result: string;
    };
    /** Resumes */
    Resumes: {
      /** Role */
      role: string;
      /** Skills */
      skills: string[];
      /** Experience */
      experience: number;
      /** Location */
      location: string;
    };
    /** Salary */
    Salary: {
      /** From */
      from: number;
      /** To */
      to: number;
    };
    /** ServiceResponse */
    ServiceResponse: {
      salary: components["schemas"]["Salary"];
      /** Recommend Vacancies */
      recommend_vacancies: components["schemas"]["Vacancies"][] | null;
      /**
       * Quality
       * @enum {string}
       */
      quality: "poor" | "moderate" | "good";
      /** Recommendations */
      recommendations: components["schemas"]["Recommendation"][];
    };
    /**
     * UserRegistrationRequest
     * @description Represents the user registration details.
     */
    UserRegistrationRequest: {
      /**
       * Username
       * @example username
       */
      username: string;
      /**
       * Password
       * @example password
       */
      password: string;
    };
    /**
     * UserResponse
     * @description Represents the public response data for a user.
     */
    UserResponse: {
      /**
       * Id
       * Format: uuid4
       */
      id: string;
      /**
       * Username
       * @example username
       */
      username: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /**
     * UserUpdatePasswordRequest
     * @description Represents the user password request details.
     */
    UserUpdatePasswordRequest: {
      /**
       * Old Password
       * @example password
       */
      old_password: string;
      /**
       * New Password
       * @example password
       */
      new_password: string;
    };
    /**
     * UserUsernameRequest
     * @description Represents the user username request details.
     */
    UserUsernameRequest: {
      /**
       * Username
       * @example username
       */
      username: string;
    };
    /**
     * UsersPaginationResponse
     * @description Represents the public response data for a list of users.
     */
    UsersPaginationResponse: {
      /** Users */
      users: components["schemas"]["UserResponse"][];
      pagination: components["schemas"]["PaginationResponse"];
    };
    /** Vacancies */
    Vacancies: {
      /** Id */
      id: string;
      /** Company Name */
      company_name: string;
      /** Vacancy Name */
      vacancy_name: string;
      experience: components["schemas"]["Experience"];
      /** Schedule */
      schedule: string;
      /** Work Hours */
      work_hours: number;
      salary: components["schemas"]["Salary"];
      /** Location */
      location: string;
      /** Description */
      description: string;
      /** Skills */
      skills: string[];
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type AccessTokenResponse = components["schemas"]["AccessTokenResponse"];
export type BodyLoginAuthLoginPost =
  components["schemas"]["Body_login_auth_login_post"];
export type CurrentUserResponse = components["schemas"]["CurrentUserResponse"];
export type Experience = components["schemas"]["Experience"];
export type HttpValidationError = components["schemas"]["HTTPValidationError"];
export type PaginationResponse = components["schemas"]["PaginationResponse"];
export type Recommendation = components["schemas"]["Recommendation"];
export type Resumes = components["schemas"]["Resumes"];
export type Salary = components["schemas"]["Salary"];
export type ServiceResponse = components["schemas"]["ServiceResponse"];
export type UserRegistrationRequest =
  components["schemas"]["UserRegistrationRequest"];
export type UserResponse = components["schemas"]["UserResponse"];
export type UserUpdatePasswordRequest =
  components["schemas"]["UserUpdatePasswordRequest"];
export type UserUsernameRequest = components["schemas"]["UserUsernameRequest"];
export type UsersPaginationResponse =
  components["schemas"]["UsersPaginationResponse"];
export type Vacancies = components["schemas"]["Vacancies"];
export type ValidationError = components["schemas"]["ValidationError"];
export type $defs = Record<string, never>;
export interface operations {
  register_auth_register_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserRegistrationRequest"];
      };
    };
    responses: {
      /** @description Registraton was successful */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AccessTokenResponse"];
        };
      };
      /** @description Username already registered */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  login_auth_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/x-www-form-urlencoded": components["schemas"]["Body_login_auth_login_post"];
      };
    };
    responses: {
      /** @description Login was successful */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AccessTokenResponse"];
        };
      };
      /** @description Incorrect username or password */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_current_user_users_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CurrentUserResponse"];
        };
      };
      /** @description Failed to verify credentials */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description User not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  update_current_user_username_users_me_username_patch: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserUsernameRequest"];
      };
    };
    responses: {
      /** @description Username successfully updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CurrentUserResponse"];
        };
      };
      /** @description Failed to verify credentials */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description User not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Username already registered */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_current_user_password_users_me_password_patch: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserUpdatePasswordRequest"];
      };
    };
    responses: {
      /** @description Password successfully updated */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Failed to verify credentials or incorrect password */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description User not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_users_users_get: {
    parameters: {
      query?: {
        q?: string | null;
        offset?: number;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UsersPaginationResponse"];
        };
      };
      /** @description No users found matching the provided search parameters */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_user_users__username__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        username: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserResponse"];
        };
      };
      /** @description No user found with the provided username */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  load_resume_resumes_analyze_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Resumes"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ServiceResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
