export const POPULAR_ROLES = [
  // ИТ и технические специальности
  "Программист",
  "Системный администратор",
  "Аналитик данных",
  "DevOps-инженер",
  "Тестировщик ПО",
  "Дизайнер интерфейсов",
  "Продукт-менеджер",
  "Инженер по кибербезопасности",
  "Разработчик игр",
  "Технический писатель",

  // Бизнес и управление
  "Директор",
  "Бухгалтер",
  "Юрист",
  "HR-менеджер",
  "Маркетолог",
  "Продавец",
  "Логист",
  "Предприниматель",
  "Финансовый аналитик",
  "Кассир",

  // Образование и наука
  "Учитель",
  "Профессор",
  "Школьный психолог",
  "Воспитатель детского сада",
  "Репетитор",
  "Научный сотрудник",
  "Библиотекарь",
  "Куратор",
  "Тренер",
  "Лектор",

  // Медицина и здравоохранение
  "Врач",
  "Медсестра",
  "Фельдшер",
  "Стоматолог",
  "Парамедик",
  "Фармацевт",
  "Психотерапевт",
  "Массажист",
  "Санитар",
  "Лаборант",

  // Промышленность и строительство
  "Сварщик",
  "Электрик",
  "Сантехник",
  "Строитель",
  "Машинист",
  "Токарь",
  "Инженер",
  "Геодезист",
  "Монтажник",
  "Крановщик",

  // Транспорт и логистика
  "Водитель",
  "Таксист",
  "Пилот",
  "Машинист поезда",
  "Диспетчер",
  "Курьер",
  "Грузчик",
  "Экспедитор",
  "Автослесарь",
  "Дальнобойщик",

  // Сфера услуг и быт
  "Повар",
  "Официант",
  "Бариста",
  "Парикмахер",
  "Косметолог",
  "Уборщик",
  "Дворник",
  "Сторож",
  "Горничная",
  "Флорист",

  // Творчество и медиа
  "Журналист",
  "Фотограф",
  "Актёр",
  "Музыкант",
  "Художник",
  "Видеомонтажёр",
  "Блогер",
  "Сценарист",
  "Режиссёр",
  "Ведущий",

  // Госслужба и силовые структуры
  "Полицейский",
  "Пожарный",
  "Солдат",
  "Таможенник",
  "Пограничник",
  "Судья",
  "Прокурор",
  "Нотариус",
  "Инспектор ГИБДД",
  "Почтальон",

  // Мемные и ироничные роли (но реально употребляемые)
  "Носитель чая",
  "Носитель кофе",
  "Мама в декрете",
  "Студент",
  "Безработный с потенциалом",
  "Коуч",
  "Тимлид (на кухне)",
  "Специалист по поддержке родственников",
  "Эксперт по выживанию в метро",
  "Главный по настроению",

  // --- Software Engineering ---
  "Frontend-разработчик",
  "Backend-разработчик",
  "Fullstack-разработчик",
  "Mobile Developer (iOS)",
  "Mobile Developer (Android)",
  "React Native Developer",
  "Flutter Developer",
  "DevOps Engineer",
  "Site Reliability Engineer (SRE)",
  "Embedded Systems Developer",
  "Game Developer",
  "Blockchain Developer",
  "Quant Developer",
  "Firmware Engineer",
  "Kernel Developer",
  "Systems Programmer",
  "Compiler Engineer",
  "Rust Developer",
  "Go Developer",
  "Python Developer",
  "Java Developer",
  "C# Developer",
  "C++ Developer",
  "Scala Developer",
  "TypeScript Developer",
  ".NET Developer",
  "PHP Developer",
  "Ruby on Rails Developer",
  "Node.js Developer",
  "WebAssembly Developer",

  // --- Data & Analytics ---
  "Data Scientist",
  "Machine Learning Engineer",
  "Deep Learning Engineer",
  "NLP Engineer",
  "Computer Vision Engineer",
  "Data Engineer",
  "Analytics Engineer",
  "BI Developer",
  "Business Analyst",
  "Product Analyst",
  "Marketing Analyst",
  "Data Analyst",
  "Research Scientist (AI/ML)",
  "MLOps Engineer",
  "Data Architect",
  "ETL Developer",
  "CRM Analyst",
  "Web Analyst",
  "Pricing Analyst",
  "Risk Analyst",

  // --- Product & Management ---
  "Product Manager",
  "Technical Product Manager",
  "Growth Product Manager",
  "Platform Product Manager",
  "AI Product Manager",
  "Product Owner",
  "Scrum Master",
  "Project Manager",
  "Technical Program Manager",
  "Delivery Manager",
  "Chief Product Officer (CPO)",
  "Product Designer (см. дизайн)",
  "UX Researcher",
  "User Researcher",
  "Product Marketing Manager",
  "Customer Success Manager",
  "Solutions Architect",
  "Enterprise Architect",
  "IT Consultant",
  "Digital Transformation Consultant",

  // --- Design (UX/UI, Motion, Brand) ---
  "UI Designer",
  "UX Designer",
  "Product Designer",
  "Interaction Designer",
  "Visual Designer",
  "Motion Designer",
  "Graphic Designer",
  "Brand Designer",
  "Design Systems Designer",
  "Service Designer",
  "Information Architect",
  "UX Writer",
  "Content Designer",
  "DesignOps Specialist",
  "Creative Technologist",
  "3D Designer (для продуктов)",
  "Prototyper (Figma/ProtoPie)",
  "Design Lead",
  "Head of Design",
  "Accessibility Specialist (Design)",

  // --- QA & Testing ---
  "QA Engineer",
  "Manual Tester",
  "Automation QA Engineer",
  "SDET (Software Development Engineer in Test)",
  "Performance Tester",
  "Security Tester",
  "QA Lead",
  "Test Architect",
  "Mobile QA Engineer",
  "Game Tester",

  // --- Cybersecurity ---
  "Security Engineer",
  "Application Security Engineer (AppSec)",
  "Cloud Security Engineer",
  "Security Analyst",
  "Penetration Tester (Ethical Hacker)",
  "SOC Analyst",
  "Security Architect",
  "GRC Specialist (Governance, Risk, Compliance)",
  "DevSecOps Engineer",
  "Incident Responder",

  // --- Cloud & Infrastructure ---
  "Cloud Engineer (AWS/Azure/GCP)",
  "Cloud Architect",
  "Platform Engineer",
  "Kubernetes Engineer",
  "Infrastructure Engineer",
  "Network Engineer",
  "Database Administrator (DBA)",
  "PostgreSQL DBA",
  "MySQL DBA",
  "MongoDB Engineer",
  "Data Platform Engineer",

  // --- Emerging & Niche ---
  "AI Ethics Specialist",
  "Prompt Engineer",
  "AR/VR Developer",
  "IoT Developer",
  "Quantum Computing Researcher",
  "Bioinformatics Engineer",
  "FinTech Developer",
  "AdTech Engineer",
  "MarTech Engineer",
  "Low-Code Developer",
  "No-Code Specialist",
  "API Designer",
  "Integration Specialist",
  "Real-Time Systems Engineer",
  "Observability Engineer",

  // --- Leadership & Strategy ---
  "CTO",
  "CIO",
  "VP of Engineering",
  "Head of Data",
  "Director of Product",
  "Engineering Manager",
  "Tech Lead",
  "Principal Engineer",
  "Staff Engineer",
  "Distinguished Engineer",
] as const;
