export const RESUME_SKILLS_MIN_COUNT = 1;
export const RESUME_SKILLS_MAX_COUNT = 100;

export const POPULAR_SKILLS = [
  // === Программирование и языки ===
  "JavaScript",
  "TypeScript",
  "Python",
  "Java",
  "C#",
  "C++",
  "Go (Golang)",
  "Rust",
  "PHP",
  "Ruby",
  "Kotlin",
  "Swift",
  "Scala",
  "R",
  "SQL",
  "NoSQL",
  "GraphQL",
  "HTML5",
  "CSS3",
  "Sass/SCSS",
  "Bash/Shell",
  "PowerShell",
  "Lua",
  "Dart",
  "Haskell",
  "Elixir",
  "Clojure",
  "Perl",
  "Objective-C",
  "Assembly",

  // === Фреймворки и библиотеки ===
  "React",
  "Vue.js",
  "Angular",
  "Svelte",
  "Next.js",
  "Nuxt.js",
  "Redux",
  "Zustand",
  "MobX",
  "Spring Boot",
  "Django",
  "Flask",
  "FastAPI",
  "Express.js",
  "NestJS",
  "ASP.NET Core",
  "Laravel",
  "Symfony",
  "Ruby on Rails",
  ".NET MAUI",
  "Flutter",
  "React Native",
  "Xamarin",
  "jQuery",
  "Three.js",
  "D3.js",
  "TensorFlow",
  "PyTorch",
  "Keras",
  "Scikit-learn",

  // === DevOps и инфраструктура ===
  "Docker",
  "Kubernetes",
  "Helm",
  "Terraform",
  "Ansible",
  "Chef",
  "Puppet",
  "Jenkins",
  "GitLab CI/CD",
  "GitHub Actions",
  "CircleCI",
  "ArgoCD",
  "Prometheus",
  "Grafana",
  "ELK Stack",
  "Sentry",
  "Datadog",
  "New Relic",
  "AWS",
  "Azure",
  "Google Cloud Platform (GCP)",
  "Yandex Cloud",
  "Cloudflare",
  "Nginx",
  "Apache",
  "HAProxy",
  "Istio",
  "Consul",
  "Vault",
  "RabbitMQ",

  // === Базы данных ===
  "PostgreSQL",
  "MySQL",
  "MariaDB",
  "MongoDB",
  "Redis",
  "Elasticsearch",
  "ClickHouse",
  "Cassandra",
  "Couchbase",
  "SQLite",
  "Oracle Database",
  "Microsoft SQL Server",
  "DynamoDB",
  "Firestore",
  "BigQuery",
  "Snowflake",
  "Redshift",
  "Apache Kafka",
  "Apache Flink",
  "Apache Spark",

  // === Data Science & Analytics ===
  "Data Analysis",
  "Machine Learning",
  "Deep Learning",
  "Natural Language Processing (NLP)",
  "Computer Vision",
  "Time Series Forecasting",
  "A/B Testing",
  "Statistical Analysis",
  "Data Visualization",
  "ETL/ELT",
  "Feature Engineering",
  "Model Deployment",
  "MLOps",
  "Data Warehousing",
  "Looker",
  "Tableau",
  "Power BI",
  "Metabase",
  "Superset",
  "Excel (Advanced)",

  // === Продукт и управление ===
  "Product Management",
  "User Story Mapping",
  "Jobs-to-be-Done (JTBD)",
  "PRD Writing",
  "Roadmap Planning",
  "Backlog Grooming",
  "Agile",
  "Scrum",
  "Kanban",
  "Lean Startup",
  "Design Thinking",
  "OKR",
  "KPI Definition",
  "Customer Development",
  "Market Research",
  "Competitive Analysis",
  "Go-to-Market Strategy",
  "Pricing Strategy",
  "Monetization Strategy",
  "UX Strategy",

  // === Дизайн и UX/UI ===
  "UI Design",
  "UX Design",
  "Wireframing",
  "Prototyping",
  "User Flows",
  "Information Architecture",
  "Design Systems",
  "Accessibility (WCAG)",
  "Responsive Design",
  "Mobile-First Design",
  "Figma",
  "Sketch",
  "Adobe XD",
  "Photoshop",
  "Illustrator",
  "After Effects",
  "Principle",
  "ProtoPie",
  "User Testing",
  "Heuristic Evaluation",

  // === QA и тестирование ===
  "Manual Testing",
  "Test Case Design",
  "Selenium",
  "Playwright",
  "Cypress",
  "Jest",
  "Vitest",
  "Pytest",
  "JUnit",
  "TestNG",
  "Postman",
  "Swagger/OpenAPI",
  "Load Testing",
  "Security Testing",
  "Cross-Browser Testing",
  "Mobile Testing",
  "Exploratory Testing",
  "Test Automation",
  "QA Documentation",
  "Bug Reporting",

  // === Cybersecurity ===
  "Penetration Testing",
  "OWASP Top 10",
  "Network Security",
  "Application Security (AppSec)",
  "Cloud Security",
  "Security Auditing",
  "SIEM",
  "Incident Response",
  "Zero Trust Architecture",
  "Cryptography",
  "Identity and Access Management (IAM)",
  "GDPR Compliance",
  "ISO 27001",
  "SOC 2",
  "Threat Modeling",
  "Vulnerability Scanning",
  "Burp Suite",
  "Nmap",
  "Wireshark",
  "Security Hardening",

  // === Методологии и soft skills ===
  "Командная работа",
  "Коммуникация",
  "Управление временем",
  "Критическое мышление",
  "Решение проблем",
  "Эмоциональный интеллект",
  "Лидерство",
  "Менторство",
  "Презентация",
  "Переговоры",
  "Обратная связь",
  "Адаптивность",
  "Инициативность",
  "Ответственность",
  "Организация встреч",
  "Ведение документации",
  "Постановка целей",
  "Работа в условиях неопределенности",
  "Многозадачность",
  "Самообучение",

  // === Бизнес и аналитика ===
  "Финансовый анализ",
  "Бюджетирование",
  "Бизнес-моделирование",
  "SWOT-анализ",
  "PEST-анализ",
  "Unit Economics",
  "LTV/CAC",
  "Churn Analysis",
  "Funnel Analysis",
  "Cohort Analysis",
  "CRM (Salesforce, HubSpot)",
  "ERP-системы",
  "SAP",
  "1С",
  "Google Analytics",
  "Amplitude",
  "Mixpanel",
  "Hotjar",
  "Segment",
  "Zapier",

  // === Инструменты и софт ===
  "Git",
  "Jira",
  "Confluence",
  "Notion",
  "Trello",
  "ClickUp",
  "Linear",
  "Slack",
  "Microsoft Teams",
  "Zoom",
  "Google Workspace",
  "Microsoft Office",
  "Linux",
  "macOS",
  "Windows Server",
  "DBeaver",
  "VS Code",
  "IntelliJ IDEA",
  "Android Studio",

  // === Нишевые и emerging ===
  "Prompt Engineering",
  "LLM Fine-tuning",
  "RAG (Retrieval-Augmented Generation)",
  "LangChain",
  "Vector Databases (Pinecone, Weaviate)",
  "Web3 Development",
  "Solidity",
  "Smart Contracts",
  "Blockchain Architecture",
  "AR/VR Development",
  "Unity",
  "Unreal Engine",
  "IoT Prototyping",
  "ROS (Robot Operating System)",
  "Quantum Algorithms",
  "Bioinformatics",
  "Geospatial Analysis",
  "Low-Code Platforms (Retool, OutSystems)",
  "No-Code Automation",
  "Digital Twin",

  // === Управление и лидерство ===
  "People Management",
  "Performance Reviews",
  "Hiring & Interviewing",
  "Onboarding",
  "Team Building",
  "Conflict Resolution",
  "Delegation",
  "Strategic Planning",
  "Change Management",
  "Stakeholder Management",

  // Языки
  "Русский",
  "Английский",
  "Испанский",
  "Немецкий",
  "Французский",
  "Итальянский",
  "Китайский (упрощенный)",
  "Японский",
  "Корейский",
  "Португальский",
  "Арабский",
  "Турецкий",
  "Голландский",
  "Шведский",
  "Датский",
  "Норвежский",
  "Финский",
  "Индийский (хинди)",
  "Тайский",
  "Вьетнамский",
  "Малайский",
  "Иврит",
  "Персидский",
  "Бенгальский",
  "Тамильский",
  "Каннада",
  "Урду",
  "Суахили",
  "Хорватский",
  "Сербский",
  "Румынский",
  "Чешский",
  "Словацкий",
  "Болгарский",
  "Греческий",
  "Таи",
  "Словенский",
  "Литовский",
  "Латышский",
  "Эстонский",
  "Каталонский",
  "Мальтийский",
  "Филиппинский (тагальский)",
  "Гварани",
  "Гуджарати",
  "Некоторые другие языки коренных народов",
];
